import { useState, useRef } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { queryClient, apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Upload, FileText, Zap, Copy, Download, AlertTriangle, CheckCircle, TrendingUp } from "lucide-react";
import type { User } from "@shared/schema";

interface CreditIssue {
  type: string;
  creditor: string;
  amount?: number;
  description: string;
  impact: 'HIGH' | 'MEDIUM' | 'LOW';
  suggestedAction: string;
}

interface AIAnalysis {
  creditScore: number;
  issuesFound: CreditIssue[];
  recommendations: string[];
}

interface UploadResult {
  upload: {
    id: number;
    fileName: string;
    fileType: string;
    uploadedAt: string;
  };
  aiAnalysis: AIAnalysis;
  message: string;
}

export function CreditReportUploader() {
  const [selectedUserId, setSelectedUserId] = useState<string>("");
  const [description, setDescription] = useState("");
  const [dragOver, setDragOver] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<UploadResult | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  // Fetch all users for selection
  const { data: users = [] } = useQuery<User[]>({
    queryKey: ['/api/users'],
  });

  const uploadMutation = useMutation({
    mutationFn: async (data: { userId: string; fileName: string; fileData: string; fileType: string; description: string }) => {
      const response = await apiRequest("POST", "/api/admin/upload-credit-report", JSON.stringify(data));
      return response.json();
    },
    onSuccess: (result: UploadResult) => {
      setAnalysisResult(result);
      toast({
        title: "Credit Report Analyzed",
        description: "AI analysis complete. Review the findings and generate dispute letters.",
      });
    },
    onError: (error) => {
      toast({
        title: "Upload Failed",
        description: error instanceof Error ? error.message : "Failed to upload credit report",
        variant: "destructive",
      });
    }
  });

  const generateLetterMutation = useMutation({
    mutationFn: async (data: { issue: CreditIssue; clientName: string; clientAddress?: string }) => {
      const response = await apiRequest("POST", "/api/admin/generate-dispute-letter", JSON.stringify(data));
      return response.json();
    },
    onSuccess: (result) => {
      // Open new tab with the generated letter
      const letterWindow = window.open("", "_blank");
      if (letterWindow) {
        letterWindow.document.write(`
          <html>
            <head>
              <title>Dispute Letter - ${result.clientName}</title>
              <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; margin: 40px; }
                .header { text-align: center; margin-bottom: 40px; }
                .letter { white-space: pre-line; }
                @media print { body { margin: 20px; } }
              </style>
            </head>
            <body>
              <div class="header">
                <h2>Credit Dispute Letter</h2>
                <p>Generated by ScoreShift AI - ${new Date().toLocaleDateString()}</p>
              </div>
              <div class="letter">${result.letter}</div>
            </body>
          </html>
        `);
        letterWindow.document.close();
      }
      toast({
        title: "Dispute Letter Generated",
        description: "Letter opened in new tab for printing or editing.",
      });
    }
  });

  const handleFileSelect = (file: File) => {
    if (!selectedUserId) {
      toast({
        title: "Select Client",
        description: "Please select a client before uploading the credit report.",
        variant: "destructive",
      });
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const fileData = e.target?.result as string;
      const base64Data = fileData.split(',')[1]; // Remove data:mime;base64, prefix
      
      uploadMutation.mutate({
        userId: selectedUserId,
        fileName: file.name,
        fileData: base64Data,
        fileType: file.type,
        description: description || `Credit report upload - ${file.name}`
      });
    };
    reader.readAsDataURL(file);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const files = Array.from(e.dataTransfer.files);
    if (files.length > 0) {
      handleFileSelect(files[0]);
    }
  };

  const handleFileInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      handleFileSelect(files[0]);
    }
  };

  const selectedUser = users.find(u => u.id.toString() === selectedUserId);

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center space-x-2">
            <Upload className="h-5 w-5 text-blue-600" />
            <span>Credit Report AI Analysis</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="client">Select Client</Label>
              <Select value={selectedUserId} onValueChange={setSelectedUserId}>
                <SelectTrigger>
                  <SelectValue placeholder="Choose a client..." />
                </SelectTrigger>
                <SelectContent>
                  {users.filter(u => u.accessLevel === 'CLIENT_VIEWER').map((user) => (
                    <SelectItem key={user.id} value={user.id.toString()}>
                      {user.firstName} {user.lastName} ({user.email})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label htmlFor="description">Description (Optional)</Label>
              <Input
                id="description"
                placeholder="e.g., Experian report from 1/15/2025"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>
          </div>

          {/* File Upload Area */}
          <div
            className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors ${
              dragOver ? 'border-blue-500 bg-blue-50' : 'border-gray-300'
            } ${uploadMutation.isPending ? 'opacity-50' : ''}`}
            onDrop={handleDrop}
            onDragOver={(e) => {
              e.preventDefault();
              setDragOver(true);
            }}
            onDragLeave={() => setDragOver(false)}
          >
            {uploadMutation.isPending ? (
              <div className="flex items-center justify-center space-x-2">
                <div className="animate-spin rounded-full h-6 w-6 border-2 border-blue-600 border-t-transparent"></div>
                <span className="text-blue-600">Analyzing credit report with AI...</span>
              </div>
            ) : (
              <>
                <FileText className="h-12 w-12 mx-auto mb-4 text-gray-400" />
                <h3 className="text-lg font-medium text-gray-900 mb-2">
                  Upload Credit Report or Screenshot
                </h3>
                <p className="text-gray-600 mb-4">
                  Drag and drop your file here, or click to browse
                </p>
                <p className="text-sm text-gray-500 mb-4">
                  Supports: PDF, PNG, JPG, JPEG (Max 10MB)
                </p>
                <Button
                  onClick={() => fileInputRef.current?.click()}
                  disabled={!selectedUserId || uploadMutation.isPending}
                >
                  <Upload className="h-4 w-4 mr-2" />
                  Choose File
                </Button>
                <input
                  ref={fileInputRef}
                  type="file"
                  className="hidden"
                  accept=".pdf,.png,.jpg,.jpeg"
                  onChange={handleFileInput}
                />
              </>
            )}
          </div>
        </CardContent>
      </Card>

      {/* AI Analysis Results */}
      {analysisResult && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Zap className="h-5 w-5 text-yellow-600" />
                <span>AI Analysis Results</span>
                <Badge variant="secondary">{analysisResult.aiAnalysis.issuesFound.length} Issues Found</Badge>
              </div>
              <Badge className="bg-blue-100 text-blue-800">
                Credit Score: {analysisResult.aiAnalysis.creditScore}
              </Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <Tabs defaultValue="issues" className="w-full">
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="issues">Issues Found</TabsTrigger>
                <TabsTrigger value="recommendations">Recommendations</TabsTrigger>
                <TabsTrigger value="letters">Generate Letters</TabsTrigger>
              </TabsList>

              <TabsContent value="issues" className="space-y-4">
                {analysisResult.aiAnalysis.issuesFound.map((issue, index) => (
                  <Card key={index} className="border-l-4 border-l-red-500">
                    <CardContent className="p-4">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center space-x-2">
                          <Badge variant={issue.impact === 'HIGH' ? 'destructive' : issue.impact === 'MEDIUM' ? 'default' : 'secondary'}>
                            {issue.impact} Impact
                          </Badge>
                          <span className="font-medium">{issue.type.replace('_', ' ')}</span>
                        </div>
                        {issue.amount && (
                          <span className="font-bold text-lg">${issue.amount.toLocaleString()}</span>
                        )}
                      </div>
                      <p className="text-gray-700 mb-2">
                        <strong>{issue.creditor}:</strong> {issue.description}
                      </p>
                      <p className="text-sm text-blue-600">
                        <strong>Suggested Action:</strong> {issue.suggestedAction}
                      </p>
                    </CardContent>
                  </Card>
                ))}
              </TabsContent>

              <TabsContent value="recommendations" className="space-y-4">
                <div className="bg-green-50 p-4 rounded-lg">
                  <h4 className="font-medium text-green-800 mb-3 flex items-center">
                    <TrendingUp className="h-4 w-4 mr-2" />
                    AI Recommendations
                  </h4>
                  <ul className="space-y-2">
                    {analysisResult.aiAnalysis.recommendations.map((rec, index) => (
                      <li key={index} className="flex items-start space-x-2">
                        <CheckCircle className="h-4 w-4 text-green-600 mt-0.5" />
                        <span className="text-green-700">{rec}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </TabsContent>

              <TabsContent value="letters" className="space-y-4">
                <div className="grid gap-4">
                  {analysisResult.aiAnalysis.issuesFound.map((issue, index) => (
                    <div key={index} className="flex items-center justify-between p-4 border rounded-lg">
                      <div>
                        <p className="font-medium">{issue.creditor} - {issue.type.replace('_', ' ')}</p>
                        <p className="text-sm text-gray-600 dark:text-gray-300">{issue.description}</p>
                      </div>
                      <Button
                        size="sm"
                        onClick={() => {
                          if (selectedUser) {
                            generateLetterMutation.mutate({
                              issue,
                              clientName: `${selectedUser.firstName} ${selectedUser.lastName}`,
                            });
                          }
                        }}
                        disabled={generateLetterMutation.isPending}
                      >
                        <FileText className="h-4 w-4 mr-2" />
                        Generate Letter
                      </Button>
                    </div>
                  ))}
                </div>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>
      )}
    </div>
  );
}